package io.github.siddhantpanhalkar.kmprofiler.report

import io.github.siddhantpanhalkar.kmprofiler.model.ConfigLintResult
import io.github.siddhantpanhalkar.kmprofiler.model.DeclarationKind
import io.github.siddhantpanhalkar.kmprofiler.model.DeclarationScanResult
import io.github.siddhantpanhalkar.kmprofiler.model.ScanResult
import io.github.siddhantpanhalkar.kmprofiler.ownership.RemediationCategory

object MarkdownReportRenderer {

    fun render(result: ScanResult): String = buildString {
        appendLine("### kmprofiler: iOS Export Profile")
        appendLine()
        appendLine("**Export surface:** ${result.totalExported} Kotlin declarations exported to Objective-C.")

        val totalUnreferenced = result.reviewCandidates.size +
                result.kotlinFileFacadeCandidates.size +
                result.likelyExternalCandidates.size

        if (totalUnreferenced == 0) {
            appendLine("**All exported declarations have at least one direct call site in the scanned Swift sources.**")
        } else {
            appendLine("**No direct Swift call site found for $totalUnreferenced of them.**")
        }

        appendLine()
        appendLine("> This report identifies review candidates, not proven dead code or safe")
        appendLine("> optimizations. A declaration without a textual Swift call site may still be")
        appendLine("> used via dependency injection, protocol conformance, dynamic dispatch,")
        appendLine("> Objective-C consumers, tests, or downstream framework consumers.")
        appendLine()
        appendLine("> Kotlin visibility changes (`internal`, `private`) alter the Kotlin API and")
        appendLine("> remove the declaration from Objective-C export. Declaration-level")
        appendLine("> `@HiddenFromObjC` preserves Kotlin visibility but removes eligible")
        appendLine("> declarations from Objective-C/Swift export. Neither is automatically safe")
        appendLine("> merely because a Swift text search found no call site.")

        // Scan provenance.
        appendLine()
        appendLine("#### Provenance")
        if (result.headerPath.isNotEmpty()) {
            appendLine("- **Header:** `${result.headerPath}`")
        }
        if (result.headerTimestamp > 0) {
            appendLine("- **Header modified:** ${java.time.Instant.ofEpochMilli(result.headerTimestamp)}")
        }
        appendLine("- **Swift files scanned:** ${result.scannedFileCount}")
        appendLine("- **Swift lines scanned:** ${result.scannedLineCount}")
        appendLine("- **Scan coverage:** This scanner covers only the configured Swift source directories.")
        appendLine("  It does not cover Objective-C files, tests, generated Swift, or downstream consumers.")
        appendLine("- **Ownership analysis:** Heuristic-based (no Kotlin compiler metadata).")
        appendLine("  All remediation recommendations are `MANUAL_REVIEW_ONLY` until KLIB integration is available.")

        // App declarations.
        if (result.reviewCandidates.isNotEmpty()) {
            appendLine()
            appendLine("#### Your code - review candidates (${result.reviewCandidates.size})")
            appendLine()
            appendLine("No direct call site found in scanned Swift sources.")
            appendLine()
            renderDeclarationTable(this, result.reviewCandidates, result.remediation)
            appendLine()
            renderDecisionTree(this)
            renderExternalPrefixTip(this)
        }

        // Kotlin file facades.
        if (result.kotlinFileFacadeCandidates.isNotEmpty()) {
            appendLine()
            appendLine("#### Kotlin file facades - review candidates (${result.kotlinFileFacadeCandidates.size})")
            appendLine()
            appendLine("These `*Kt` classes are generated by Kotlin/Native for source files containing")
            appendLine("top-level functions (e.g. `ColorKt` wraps `Color.kt`).")
            appendLine()
            appendLine("If iOS never uses these functions directly, review eligible individual")
            appendLine("declarations for declaration-level `@HiddenFromObjC` or visibility changes.")
            appendLine("Do not apply file-level annotations - `@HiddenFromObjC` targets classes,")
            appendLine("functions, and properties, not files.")
            appendLine()
            renderFacadeTable(this, result.kotlinFileFacadeCandidates, result.remediation)
        }

        // Declarations with unresolved ownership.
        if (result.likelyExternalCandidates.isNotEmpty()) {
            appendLine()
            appendLine("#### Unresolved ownership - ${result.likelyExternalCandidates.size} declarations")
            appendLine()
            appendLine("These declarations' names match Kotlin/Native cross-module ObjC name mangling")
            appendLine("(`ModuleName_submoduleTypeName`) or a user-configured external prefix. Ownership")
            appendLine("is inferred from naming heuristics, not metadata.")
            appendLine()
            appendLine("Do not attempt to edit these as if they were your code. Instead:")
            appendLine("- Ensure `transitiveExport = false` (already correct if shown in Config below)")
            appendLine("- Remove any explicit `export(deps.someLibrary)` from your `binaries.framework {}` block")
            appendLine("- Re-link the framework and confirm the header delta")
            appendLine()
            renderExternalTable(this, result.likelyExternalCandidates)
        }

        appendLine()
        appendLine("#### Config")
        appendConfigLint(result.configLint)
    }

    private fun renderDeclarationTable(
        sb: StringBuilder,
        candidates: List<DeclarationScanResult>,
        remediation: Map<String, RemediationCategory>,
    ) {
        sb.appendLine("| Declaration | Kind | Members | Confidence | Remediation | Evidence |")
        sb.appendLine("|---|---|---|---|---|---|")
        candidates.sortedByDescending { it.memberCount }.forEach { scanResult ->
            val membersDisplay =
                if (scanResult.memberCount == 0) "0 (empty)" else "${scanResult.memberCount}"
            val confidence = scanResult.confidence.name.lowercase()
            val remediationLabel = remediation[scanResult.name]?.let { cat ->
                cat.name.lowercase().replace("_", " ")
            } ?: "unknown"
            val evidenceSummary = formatEvidence(scanResult)
            sb.appendLine("| `${scanResult.name}` | ${scanResult.kind.label()} | $membersDisplay | $confidence | $remediationLabel | $evidenceSummary |")
        }
    }

    private fun renderFacadeTable(
        sb: StringBuilder,
        candidates: List<DeclarationScanResult>,
        remediation: Map<String, RemediationCategory>,
    ) {
        sb.appendLine("| Declaration | Members | Confidence | Remediation | Evidence |")
        sb.appendLine("|---|---|---|---|---|")
        candidates.sortedByDescending { it.memberCount }.forEach { scanResult ->
            val membersDisplay =
                if (scanResult.memberCount == 0) "0 (empty)" else "${scanResult.memberCount}"
            val confidence = scanResult.confidence.name.lowercase()
            val remediationLabel = remediation[scanResult.name]?.let { cat ->
                cat.name.lowercase().replace("_", " ")
            } ?: "unknown"
            val evidenceSummary = formatEvidence(scanResult)
            sb.appendLine("| `${scanResult.name}` | $membersDisplay | $confidence | $remediationLabel | $evidenceSummary |")
        }
    }

    private fun renderExternalTable(sb: StringBuilder, candidates: List<DeclarationScanResult>) {
        sb.appendLine("| Declaration | Members | Confidence | Evidence |")
        sb.appendLine("|---|---|---|---|")
        candidates.sortedByDescending { it.memberCount }.forEach { scanResult ->
            val membersDisplay =
                if (scanResult.memberCount == 0) "0 (empty)" else "${scanResult.memberCount}"
            val confidence = scanResult.confidence.name.lowercase()
            val evidenceSummary = formatEvidence(scanResult)
            sb.appendLine("| `${scanResult.name}` | $membersDisplay | $confidence | $evidenceSummary |")
        }
    }

    private fun formatEvidence(scanResult: DeclarationScanResult): String {
        return if (scanResult.evidence.isNotEmpty()) {
            scanResult.evidence.joinToString("; ") { ev ->
                val shortPath = ev.filePath.substringAfterLast("/")
                "${ev.matchKind.name.lowercase()} @ ${shortPath}:${ev.lineNumber}"
            }
        } else {
            "none"
        }
    }

    private fun renderDecisionTree(sb: StringBuilder) {
        sb.appendLine("**Decision tree for each candidate:**")
        sb.appendLine()
        sb.appendLine("1. **Is this declaration intentionally part of the public Kotlin API?**")
        sb.appendLine("   - Yes → keep it public. If Apple consumers must not see it, consider")
        sb.appendLine("     declaration-level `@HiddenFromObjC` and inspect every exported API")
        sb.appendLine("     that references it.")
        sb.appendLine("   - No → continue.")
        sb.appendLine("2. **Is it used across Kotlin files/source sets within the same module?**")
        sb.appendLine("   - Yes → `internal` may be appropriate, subject to the public-API graph check.")
        sb.appendLine("   - No, only in the same file/class → `private` may be appropriate.")
        sb.appendLine("3. **Does any public/protected declaration expose or inherit it?**")
        sb.appendLine("   - Yes → do not change only this declaration. Decide whether to")
        sb.appendLine("     hide/internalize the complete API chain or keep it public.")
        sb.appendLine("   - No → apply the selected visibility change and compile all affected targets.")
        sb.appendLine("4. **Is it a top-level function/property in a generated `*Kt` facade?**")
        sb.appendLine("   - Annotate eligible individual declarations with `@HiddenFromObjC`,")
        sb.appendLine("     not the file. If even one top-level declaration is needed by Swift,")
        sb.appendLine("     keep that declaration exported.")
        sb.appendLine("5. **Is ownership external or unresolved?**")
        sb.appendLine("   - Do not suggest editing dependency source. Report the dependency/export")
        sb.appendLine("     path for review.")
        sb.appendLine()
        sb.appendLine("After changes: re-link the same release framework, rerun this task, and")
        sb.appendLine("confirm the expected header delta.")
        sb.appendLine()
        sb.appendLine("> Declaration-level `@HiddenFromObjC` example:")
        sb.appendLine("> ```kotlin")
        sb.appendLine("> @OptIn(kotlin.experimental.ExperimentalObjCRefinement::class)")
        sb.appendLine("> @kotlin.native.HiddenFromObjC")
        sb.appendLine("> fun kotlinOnlyOperation() = Unit")
        sb.appendLine("> ```")
        sb.appendLine("> The exact opt-in/import form must be compiled against every Kotlin version")
        sb.appendLine("> supported by the plugin.")
    }

    private fun renderExternalPrefixTip(sb: StringBuilder) {
        sb.appendLine()
        sb.appendLine("> 💡 Seeing names you didn't write (e.g. SDK types like `SkikoCanvas` or `ModelsCustomerInfo`)?")
        sb.appendLine("> Those are likely from libraries. Add their name prefix to `externalPrefixes`")
        sb.appendLine("> in your `kmprofiler {}` block and they will move to the 'Unresolved ownership'")
        sb.appendLine("> section on next run:")
        sb.appendLine("> ```kotlin")
        sb.appendLine("> kmprofiler {")
        sb.appendLine(">     externalPrefixes.addAll(\"Skiko\", \"Models\")")
        sb.appendLine("> }")
        sb.appendLine("> ```")
    }

    private fun StringBuilder.appendConfigLint(lint: ConfigLintResult) {
        when (lint.transitiveExport) {
            true -> appendLine("- ❌ `transitiveExport = true` (configured in kmprofiler) - not recommended; pulls all transitive dependencies of exported deps into the framework.")
            false -> appendLine("- ✅ `transitiveExport = false` (configured in kmprofiler) - correct default.")
            null -> appendLine("- ℹ️ `transitiveExport` - not explicitly set (defaults to `false`).")
        }

        when (lint.isStatic) {
            true -> appendLine("- ℹ️ `isStatic = true` (configured in kmprofiler) - app-linker dead-stripping applies; raw framework size can overstate the app delta.")
            false -> appendLine("- ℹ️ `isStatic = false` (configured in kmprofiler) - dynamic linkage; the thinned framework is embedded. This can be useful for modules with C/ObjC++ dependencies.")
            null -> appendLine("- ℹ️ `isStatic` - not explicitly set; check Xcode `Embed Frameworks` settings.")
        }

        when {
            lint.exportedFrameworkCount > 1 ->
                appendLine("- ⚠️ ${lint.exportedFrameworkCount} frameworks declared to the profiler. Each is compiled independently - shared external types (for example, coroutines) may be duplicated across binaries.")

            lint.exportedFrameworkCount == 1 ->
                appendLine("- ✅ 1 framework declared to the profiler; no cross-framework type duplication detected.")

            else ->
                appendLine("- ℹ️ No exported frameworks declared to the profiler (check your `binaries.framework {}` block).")
        }
    }

    private fun DeclarationKind.label() = when (this) {
        DeclarationKind.CLASS -> "class"
        DeclarationKind.PROTOCOL -> "protocol"
        DeclarationKind.INTERFACE -> "interface"
    }
}
