package io.github.siddhantpanhalkar.kmprofiler.report

import io.github.siddhantpanhalkar.kmprofiler.model.ConfigLintResult
import io.github.siddhantpanhalkar.kmprofiler.model.DeclarationKind
import io.github.siddhantpanhalkar.kmprofiler.model.ScanResult

object MarkdownReportRenderer {

    fun render(result: ScanResult): String = buildString {
        appendLine("### 📊 KMP iOS Export Profile — v0.1")
        appendLine()
        appendLine("**Export surface:** ${result.totalExported} Kotlin declarations exported to Objective-C.")

        val totalUnreferenced = result.reviewCandidates.size +
                result.kotlinFileFacadeCandidates.size +
                result.likelyExternalCandidates.size

        if (totalUnreferenced == 0) {
            appendLine("**All exported declarations have at least one direct call site in the scanned Swift sources.** ✅")
        } else {
            appendLine("**No direct Swift call site found for $totalUnreferenced of them.**")
        }

        appendLine()
        appendLine("> ⚠️ App-size impact not yet measured. Enable `Write Link Map File` in Xcode")
        appendLine("> and re-run with `--link-map` for linked byte attribution. Note that raw")
        appendLine("> `.xcframework` size is *not* your app-size delta — it includes simulator")
        appendLine("> slices and all architectures.")

        // ── Section 1: Your code ──────────────────────────────────────────────────
        if (result.reviewCandidates.isNotEmpty()) {
            appendLine()
            appendLine("#### Your code — review candidates (${result.reviewCandidates.size})")
            appendLine()
            appendLine("No direct call site found in scanned Swift sources.")
            appendLine()
            appendLine("| Declaration | Kind | Members |")
            appendLine("|---|---|---|")
            result.reviewCandidates.sortedByDescending { it.memberCount }.forEach { decl ->
                val membersDisplay =
                    if (decl.memberCount == 0) "0 (empty)" else "${decl.memberCount}"
                appendLine("| `${decl.name}` | ${decl.kind.label()} | $membersDisplay |")
            }
            appendLine()
            appendLine("Hiding these with `internal` or `@HiddenFromObjC` removes their ObjC adapters.")
            appendLine("**Verify first** — declarations used via DI, protocol conformance, or external")
            appendLine("SDK consumers will not appear as call sites here.")
            appendLine()
            appendLine("> 💡 Seeing names you didn't write (e.g. SDK types like `SkikoCanvas` or `ModelsCustomerInfo`)?")
            appendLine("> Those are library internals the auto-classifier couldn't identify automatically.")
            appendLine("> Add their name prefix to `externalPrefixes` in your `kmprofiler {}` block")
            appendLine("> and they will move to the 'Library internals' section on next run:")
            appendLine("> ```kotlin")
            appendLine("> kmprofiler {")
            appendLine(">     externalPrefixes.addAll(\"Skiko\", \"Models\")")
            appendLine("> }")
            appendLine("> ```")
        }

        // ── Section 2: Kotlin file facades ───────────────────────────────────────
        if (result.kotlinFileFacadeCandidates.isNotEmpty()) {
            appendLine()
            appendLine("#### Kotlin file facades — review candidates (${result.kotlinFileFacadeCandidates.size})")
            appendLine()
            appendLine("These `*Kt` classes are generated by Kotlin/Native for source files containing")
            appendLine("top-level functions (e.g. `ColorKt` wraps `Color.kt`). If iOS never uses these")
            appendLine("functions directly, add `@file:HiddenFromObjC` at the top of the Kotlin source file.")
            appendLine()
            appendLine("| Declaration | Members |")
            appendLine("|---|---|")
            result.kotlinFileFacadeCandidates.sortedByDescending { it.memberCount }
                .forEach { decl ->
                    val membersDisplay =
                        if (decl.memberCount == 0) "0 (empty)" else "${decl.memberCount}"
                    appendLine("| `${decl.name}` | $membersDisplay |")
                }
        }

        // ── Section 3: Likely library internals ──────────────────────────────────
        if (result.likelyExternalCandidates.isNotEmpty()) {
            appendLine()
            appendLine("#### Likely library internals — ${result.likelyExternalCandidates.size} declarations")
            appendLine()
            appendLine("These declarations match the Kotlin/Native cross-module ObjC name mangling pattern")
            appendLine("(`ModuleName_submoduleTypeName`) or a user-configured external prefix.")
            appendLine("They originate from transitive dependencies, not your Kotlin code.")
            appendLine()
            appendLine("**You cannot hide these with `internal` or `@HiddenFromObjC`.**")
            appendLine("To remove them from your framework header:")
            appendLine("- Ensure `transitiveExport = false` (already correct if shown in Config below)")
            appendLine("- Remove any explicit `export(deps.someLibrary)` from your `binaries.framework {}` block")
            appendLine()
            appendLine("| Declaration | Members |")
            appendLine("|---|---|")
            result.likelyExternalCandidates.sortedByDescending { it.memberCount }.forEach { decl ->
                val membersDisplay =
                    if (decl.memberCount == 0) "0 (empty)" else "${decl.memberCount}"
                appendLine("| `${decl.name}` | $membersDisplay |")
            }
        }

        appendLine()
        appendLine("#### Config")
        appendConfigLint(result.configLint)
    }

    private fun StringBuilder.appendConfigLint(lint: ConfigLintResult) {
        when (lint.transitiveExport) {
            true -> appendLine("- ❌ `transitiveExport = true` — not recommended; pulls all transitive dependencies of exported deps into the framework.")
            false -> appendLine("- ✅ `transitiveExport = false` — correct default.")
            null -> appendLine("- ℹ️ `transitiveExport` — not explicitly set (defaults to `false`).")
        }

        when (lint.isStatic) {
            true -> appendLine("- ℹ️ `isStatic = true` — app-linker dead-stripping applies; raw framework size will substantially overstate app delta.")
            false -> appendLine("- ℹ️ `isStatic = false` — dynamic linkage; whole thinned framework is embedded. Valid for modules with C/ObjC++ dependencies.")
            null -> appendLine("- ℹ️ `isStatic` — not explicitly set; check Xcode `Embed Frameworks` settings.")
        }

        when {
            lint.exportedFrameworkCount > 1 ->
                appendLine("- ⚠️ ${lint.exportedFrameworkCount} exported frameworks detected. Each is compiled independently — shared external types (e.g. coroutines) will be duplicated across binaries.")

            lint.exportedFrameworkCount == 1 ->
                appendLine("- ✅ Single exported framework; no cross-framework type duplication detected.")

            else ->
                appendLine("- ℹ️ No exported frameworks detected (check your `binaries.framework {}` block).")
        }
    }

    private fun DeclarationKind.label() = when (this) {
        DeclarationKind.CLASS -> "class"
        DeclarationKind.PROTOCOL -> "protocol"
        DeclarationKind.INTERFACE -> "interface"
    }
}
