package io.github.siddhantpanhalkar.kmprofiler.parser

import io.github.siddhantpanhalkar.kmprofiler.model.DeclarationKind
import io.github.siddhantpanhalkar.kmprofiler.model.ExportedDeclaration

/**
 * Parses a Kotlin/Native-generated Objective-C header into [ExportedDeclaration] instances.
 *
 * Supported input forms (as generated by kotlinc-native):
 *   @interface MyClass : KotlinBase
 *   @interface MyClass (Extensions)
 *   @protocol MyProtocol
 *   @end
 *
 * Kotlin/Native emits `__attribute__((swift_name("...")))` lines immediately
 * before the `@interface`/`@protocol` they apply to, and inline on member
 * declarations. These Swift-facing names are what Swift source actually
 * references (the raw ObjC names carry the framework prefix, e.g.
 * `SharedUserRepository`), so they are used as the declaration and selector
 * names for call-site matching.
 *
 * Declarations that are not user Kotlin surface are deliberately skipped:
 *   - Bulk forward declaration lines (`@protocol A, B, C;`) — they carry no
 *     members; the real definitions appear later in the header.
 *   - Kotlin/Native runtime infrastructure (Swift names starting with `Kotlin`:
 *     KotlinBase, KotlinNumber, boxed primitives, KotlinMutableSet/Dictionary).
 *   - Category extensions on Foundation root classes (e.g. the `NSError`
 *     `kotlinException` category).
 * These cannot be hidden with `internal`/`@HiddenFromObjC` and are referenced
 * indirectly by Swift, so listing them as review candidates would be misleading.
 *
 * The parser is deliberately strict: it only recognises declarations in the
 * machine-generated format. User-authored ObjC is not a target.
 */
class ObjCHeaderParser {

    private sealed class State {
        object Idle : State()
        data class InBlock(
            val name: String,
            val kind: DeclarationKind,
            val selectors: MutableList<String> = mutableListOf(),
            var memberCount: Int = 0,
        ) : State()
    }

    /** Foundation root classes that Kotlin/Native extends with categories (not user Kotlin). */
    private val foundationRootTypes = setOf(
        "NSError", "NSObject", "NSString", "NSNumber",
        "NSArray", "NSDictionary", "NSSet", "NSValue",
    )

    private val swiftNameRegex = Regex("swift_name\\(\"([^\"]+)\"\\)")

    fun parse(headerText: String): List<ExportedDeclaration> {
        val results = mutableListOf<ExportedDeclaration>()
        // ObjC names of declarations skipped as Kotlin/Native runtime infrastructure.
        // Their category extensions (e.g. `SharedBase (SharedBaseCopying)`) are also
        // runtime surface and must be skipped too.
        val skippedRuntimeRoots = mutableSetOf<String>()
        var state: State = State.Idle
        var pendingSwiftName: String? = null

        for (raw in headerText.lineSequence()) {
            val line = raw.trim()

            // A standalone __attribute__((swift_name("..."))) applies to the
            // next @interface / @protocol block.
            if (line.startsWith("__attribute__")) {
                swiftNameRegex.find(line)?.groupValues?.getOrNull(1)?.let {
                    pendingSwiftName = it
                }
                continue
            }

            when {
                // ── Open a new declaration block ──────────────────────────────
                line.startsWith("@interface ") || line.startsWith("@protocol ") -> {
                    // Skip forward declarations — they end with ';' and may list
                    // multiple comma-separated names (bulk @protocol lists).
                    if (line.trimEnd().endsWith(";")) {
                        pendingSwiftName = null
                        continue
                    }

                    // Close any open block first (malformed input guard)
                    (state as? State.InBlock)?.let { results += it.toDeclaration() }

                    val kind = if (line.startsWith("@protocol")) DeclarationKind.PROTOCOL
                    else DeclarationKind.CLASS

                    // Extract name: first token after @interface / @protocol.
                    // Handles: "@interface Foo : Bar", "@interface Foo (Category)",
                    // "@interface Foo<Element> : Bar"
                    val nameToken = line
                        .removePrefix("@interface ")
                        .removePrefix("@protocol ")
                        .trimStart()
                        .split(" ", "(", ":", "<", ",", ";").first()
                        .trim()

                    val effectiveName = pendingSwiftName ?: nameToken
                    pendingSwiftName = null

                    val isCategory = line.substringAfter("@interface ").trimStart().contains("(")
                    val isRuntimeInfrastructure = effectiveName.startsWith("Kotlin")
                    val isFoundationCategory = isCategory &&
                            (nameToken in foundationRootTypes || nameToken in skippedRuntimeRoots)

                    if (isRuntimeInfrastructure) {
                        skippedRuntimeRoots += nameToken
                        state = State.Idle
                        continue
                    }
                    if (isFoundationCategory) {
                        state = State.Idle
                        continue
                    }

                    state = State.InBlock(name = effectiveName, kind = kind)
                }

                // ── Close the open block ──────────────────────────────────────
                line == "@end" -> {
                    (state as? State.InBlock)?.let { results += it.toDeclaration() }
                    state = State.Idle
                }

                // ── Member lines inside a block ───────────────────────────────
                state is State.InBlock && (line.startsWith("-") || line.startsWith("+")) -> {
                    val block = state
                    block.memberCount++
                    extractSelector(line)?.let { block.selectors += it }
                }

                // ── Property lines ────────────────────────────────────────────
                state is State.InBlock && line.startsWith("@property") -> {
                    state.memberCount++
                }
            }
        }

        // Unclosed final block (malformed but tolerated)
        (state as? State.InBlock)?.let { results += it.toDeclaration() }

        return results
    }

    /**
     * Extracts the selector used for call-site matching. Prefers the
     * Swift-facing name emitted by Kotlin/Native (`swift_name("getUser(id:)")`)
     * over the raw ObjC selector, because Swift code references the former.
     * Falls back to the ObjC selector when no swift_name attribute is present.
     *
     * Examples:
     *   `- (void)doSomethingWithA:(NSString *)a b:(int32_t)b;`  → `doSomethingWithA:b:`
     *   `- (instancetype)init;`                                  → `init`
     *   `- (NSString *)getUserId:(NSString *)id __attribute__((swift_name("getUser(id:)")));`
     *                                                             → `getUser(id:)`
     */
    private fun extractSelector(line: String): String? {
        swiftNameRegex.find(line)?.groupValues?.getOrNull(1)?.let { return it }

        // Strip leading +/- and return type: everything before the first unbalanced word token
        val body = line.removePrefix("-").removePrefix("+").trim()
        val afterReturn = body.substringAfter(")")
            .substringBefore("__attribute__")
            .trim()
        if (afterReturn.isBlank()) return null

        return buildString {
            var i = 0
            while (i < afterReturn.length && afterReturn[i] != ';') {
                val ch = afterReturn[i]
                when {
                    ch == ':' -> {
                        append(':'); i++
                    }

                    ch == '(' -> { // skip parameter type
                        var depth = 1; i++
                        while (i < afterReturn.length && depth > 0) {
                            if (afterReturn[i] == '(') depth++
                            else if (afterReturn[i] == ')') depth--
                            i++
                        }
                        // skip parameter name
                        while (i < afterReturn.length && afterReturn[i] !in " :;") i++
                    }

                    ch == ' ' || ch == '\t' -> i++
                    else -> {
                        val start = i
                        while (i < afterReturn.length && afterReturn[i] !in " :(;") i++
                        append(afterReturn.substring(start, i))
                    }
                }
            }
        }.ifBlank { null }
    }

    private fun State.InBlock.toDeclaration() = ExportedDeclaration(
        name = name,
        kind = kind,
        selectors = selectors.toList(),
        memberCount = memberCount,
    )
}